package brownies;
/** 
 * This class is used to create brownies as
 * objects within the programme.
 * Brownie objects are intantiated with a string name
 * The brownie class stores the "friends" the Brownie has declared 
 * i.e. other brownies she says likes. This class also has a
 * popularity score for the brownie, which depends on the 
 * context of the camp that the Brownie will be part of i.e. 
 * the popularity score is generated by the camp class.
 * Brownies also have a name (string) and - just for fun - a
 * thing (string) that they say
 *
 * @author Alex Peden
 *
 */



public class Brownie {
	private String brownie_name;
	private String[]friends;//The people the brownie says she likes
	private double popularity; //depends on the context of the camp
	
	/**Creates a brownie with a name and an array for storing friends
	 *
	 * @param name
	 */
	Brownie(String name){
		brownie_name = name;
		friends = new String[3];
	}
	
	void sayHello() {
		System.out.println("I'm "+brownie_name);
	}
	
	
	public String toString() {
		return brownie_name;
	}
	
	/**Used by the leader class to set the brownie popularity score
	 * This should be a double in case a complicated formula is used
	 * to calculate the popularity
	 * 
	 * @param popularity_score
	 */	
	void setPopularity(double popularity_score) {
		popularity = popularity_score;
	}

	double getPopularity() {
		return popularity;
	}
	
	void setFriends(int i, String name) {
		friends[i] = name;
	}
	
	String[] getFriends() {
		return friends;
	}
		
	public static void main(String[] args) {
		// TODO Auto-generated method stub
	}
}
